### POST 
POST http://localhost:3040/api/family
Content-Type: application/json

{
    "name":"Kiran Ali",
    "birthday":"1996-05-12",
    "age":"27"
}


### PUT
PUT http://localhost:3040/api/family/2
Content-Type: application/json

{
    "name": "Kiran Naqash",
    "birthday": "1996-05-12",
    "age": 27
}

### PATCH
PATCH http://localhost:3040/api/family/2
Content-Type: application/json

{
    "age":57
}

### DELETE
DELETE http://localhost:3040/api/family/2